src/models/Zone.php
<?php
/**
 * Created by PhpStorm.
 * User: cgarcia
 * Date: 27/12/16
 * Time: 16:47
 */

namespace quoma\arya\zone\models;

use quoma\arya\zone\ZoneModule;

/**
 * This is the model class for table "zone".
 *
 * @property integer $zone_id
 * @property string $name
 *
 * @property ZoneMember[] $zoneMembers
 */
class Zone extends \quoma\core\db\ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'zone';
    }

    /**
     * @inheritdoc
     */
    /*
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    yii\db\ActiveRecord::EVENT_BEFORE_INSERT => ['timestamp'],
                ],
            ],
            'date' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    yii\db\ActiveRecord::EVENT_BEFORE_INSERT => ['date'],
                ],
                'value' => function(){return date('Y-m-d');},
            ],
            'time' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    yii\db\ActiveRecord::EVENT_BEFORE_INSERT => ['time'],
                ],
                'value' => function(){return date('h:i');},
            ],
        ];
    }
    */

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'zone_id' => ZoneModule::t('ID'),
            'name' => ZoneModule::t('Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getZoneMembers()
    {
        return $this->hasMany(ZoneMember::className(), ['zone_id' => 'zone_id']);
    }

    /**
     * @inheritdoc
     * Strong relations: None.
     */
    public function getDeletable()
    {
        return true;
    }

    /**
     * @brief Deletes weak relations for this model on delete
     * Weak relations: None.
     */
    protected function unlinkWeakRelations()
    {
        $this->unlinkAll('zoneMembers', true);
    }

    /**
     * @inheritdoc
     */
    public function beforeDelete()
    {
        if (parent::beforeDelete()) {
            if($this->getDeletable()){
                $this->unlinkWeakRelations();
                return true;
            }
        } else {
            return false;
        }
    }

    /**
     * Busca Zona por nombre
     * @param $name
     * @return array|\yii\db\ActiveRecord[]
     */
    public static function searchByName($name) {
        $query = Zone::find();

        $query->filterWhere(['like', 'name', $name]);

        return $query->all();
    }
}

src/controllers/ZoneController.php
<?php

namespace quoma\arya\zone\controllers;

use quoma\arya\zone\models\Zone;
use quoma\arya\zone\models\ZoneMember;
use quoma\core\web\Controller;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * ZoneController implements the CRUD actions for Zone model.
 */
class ZoneController extends Controller
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(),[
        ]);
    }

    /**
     * Lists all Zone models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Zone::find()->orderBy('name')
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Zone model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Zone model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Zone();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->zone_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'membersDataProvider' => null
            ]);
        }
    }

    /**
     * Updates an existing Zone model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $membersDataProvider = new ActiveDataProvider([
            'query' => $model->getZoneMembers()
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->zone_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'membersDataProvider' => $membersDataProvider
            ]);
        }
    }

    /**
     * Deletes an existing Zone model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Zone model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Zone the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Zone::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     *
     * @param int $id
     * @return json
     */
    public function actionAddMember($id)
    {
        $model = $this->findModel($id);
        $member = new ZoneMember();
        $member->load(Yii::$app->request->post());

        if($member->validate() && $member->save()){

        }

        return $this->actionUpdate($id);
    }

    /**
     * Deletes an existing AccountConfig model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDeleteMember($zone_id, $zone_member_id)
    {
        $modelDelete = ZoneMember::findOne([
            'zone_member_id'=> $zone_member_id]);
        if(!empty($modelDelete)) {
            $modelDelete->delete();
        }

        return $this->actionUpdate($zone_id);
    }

    public function actionZoneByName($name)
    {
        if (Yii::$app->request->isAjax) {
            $zones = Zone::searchByName($name);
            $response = array();
            foreach ($zones as $zone) {
                $response['results'][] = ['id' => $zone->zone_id, 'text' => $zone->name];
            }
            Yii::$app->response->format = Response::FORMAT_JSON;
            return $response;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

src/views/zone/_find-zone-with-autocomplete.php
<?php

use quoma\arya\zone\models\Zone;
use kartik\widgets\Select2;
use yii\helpers\Url;
use yii\web\JsExpression;

$zone_id = $model->zone_id;

$zone = Zone::findOne(['zone_id'=> $zone_id]);
$name = empty($zone) ? '' : $zone->name;

if (!isset($clear)) {
    $clear = true;
}

//Plugin options
$pluginOptions = [
    'allowClear' => $clear,
    'minimumInputLength' => 3,
    'ajax' => [
        'url' => Url::to(['/zone/zone/zone-by-name']),
        'dataType' => 'json',
        'data' => new JsExpression('function(params) { return {name:params.term}; }')
    ],
    'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
    'templateResult' => new JsExpression('function(zone) { return zone.text; }'),
    'templateSelection' => new JsExpression('function (zone) { return zone.text; }'),
    'cache' => true
];

//Con ActiveForm
if(isset($form)){
    echo $form->field($model, 'zone_id')->label(isset($label) ? $label : null)->widget(Select2::classname(), [
        'data' => [$zone_id => $name],
        'options' => ['placeholder' => Yii::t('app', 'Search')],
        'pluginOptions' => $pluginOptions,
    ]);
    
//Sin ActiveForm
}else{
    echo Select2::widget([
        'model' => $model,
        'attribute' => $zone_id,
        'data' => [$zone_id => $name],
        'options' => ['placeholder' => Yii::t('app', 'Search')],
        'pluginOptions' => $pluginOptions,
    ]);
}

?>

src/views/zone/_form.php
<?php

use quoma\arya\zone\models\Zone;
use kartik\widgets\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\ActiveForm;

/* @var $this View */
/* @var $model Zone */
/* @var $form ActiveForm */
?>

<div class="zone-form">

    <?php $form = ActiveForm::begin([
        'id'=>'zone-form']); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => 255]) ?>


    <?php ActiveForm::end();

    if(isset($membersDataProvider)) {
    ?>
    <div class="panel panel-primary">
        <div class="panel-heading" data-toggle="collapse" data-target="#panel-body-items" aria-expanded="true" aria-controls="panel-body-items">
            <h3 class="panel-title"><?= \quoma\arya\zone\ZoneModule::t('Members') ?></h3>
        </div>
        <div class="panel-body collapse in" id="panel-body-items" aria-expanded="true">
            <?php
            // Formulario para los miembros

            yii\widgets\Pjax::begin(['id' => 'members']);
            $formMember = ActiveForm::begin([
                'id'=>'add-member-form',
                'action' => ['add-member', 'id' => $model->zone_id],
                'options' => ['data-pjax' => true ]]);
                $member = new \quoma\arya\zone\models\ZoneMember();
            ?>

            <input type="hidden" name="ZoneMember[zone_id]" value="<?=$model->zone_id?>"/>

            <div class="row">
                <div class="col-sm-9 col-md-12">
                    <?= $this->render('@zone/views/location/_find-location-with-autocomplete', ['model' => $member, 'form' => $formMember, 'clear' => false]) ?>
                </div>

                <div class="col-sm-9 col-md-2">
                    <label style="display: block">&nbsp;</label>
                    <a class="btn btn-primary" id="member-add">
                        <span class="glyphicon glyphicon-plus"></span> <?= Yii::t('app', 'Add') ?>
                    </a>
                </div>
            </div>

            <?php
            ActiveForm::end();

            echo \yii\grid\GridView::widget([
                'id'=>'grid',
                'dataProvider' => $membersDataProvider,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    [
                        'header'=>\quoma\arya\zone\ZoneModule::t('Name'),
                        'value'=>function($model){
                            return $model->location->name;
                        },
                    ],
                    [
                        'value'=>function($model){
                            return \quoma\arya\zone\ZoneModule::t(ucfirst($model->location->type));
                        },
                        'header'=>\quoma\arya\zone\ZoneModule::t('Type'),
                    ],
                    [
                        'value'=>function($model){
                            return $model->location->parent ? $model->location->parent->name : '';
                        },
                        'header'=>\quoma\arya\zone\ZoneModule::t('Parent')
                    ],
                    [
                        'class' => 'quoma\core\grid\ActionColumn',
                        'template'=>'{delete}',
                        'buttons'=>[
                            'delete'=>function ($url, $model, $key) {
                                return '<a class="removeMember btn btn-danger" href="#" data-url="'.\yii\helpers\Url::toRoute(['zone/delete-member', 'zone_id'=>$model->zone_id, 'zone_member_id'=>$model->zone_member_id]).
                                    '" title="'.Yii::t('app','Delete').'" data-confirm-text="'.Yii::t('yii','Are you sure you want to delete this item?').'" ><span class="glyphicon glyphicon-trash"></span></a>';
                            }
                        ]
                    ],
                ],
                'options'=>[
                    'style'=>'margin-top:10px;'
                ]
            ]);
            ?>
            <?php \yii\widgets\Pjax::end();?>
        </div>
    </div>
    <?php } ?>

    <div class="form-group">
        <a id="saveBill" onclick="Zone.save();" class="btn <?=($model->isNewRecord ? 'btn btn-success' : 'btn btn-primary')?>">
            <!-- <span class='glyphicon glyphicon-plus'></span>              -->
            <?= ($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update')) ?>
        </a>
    </div>

</div>
    <script>
        var Zone = new function() {
            this.init = function () {
                // Eventos de impuestos
                $(document).on("click","#member-add", function(){
                    Zone.addMember();
                });
                $("#new_tax").on("pjax:end", function() {
                    $.pjax.reload({container:"#members", async:false});
                });

                $(document).on("click",".removeMember", function(event){
                    Zone.removeMember(this, event);
                });
            }

            this.addMember = function() {
                $('#add-member-form').submit();
            }

            this.removeMember = function(elem, event) {
                event.preventDefault();
                var url = $(elem).data('url');
                var confirmText = $(elem).data('confirm-text');
                if (confirm(confirmText)) {
                    $.ajax({
                        url: url,
                        type: 'post',
                    }).done(function(data) {
                        $.pjax.reload({container:"#members", async:false});
                    });
                }
            }

            this.save = function()
            {
                $('#zone-form').submit();
            }
        }
    </script>
<?php  $this->registerJs("Zone.init();"); ?>

src/views/zone/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model quoma\arya\zone\models\Zone */

$this->title = Yii::t('app', 'Create');
$this->params['breadcrumbs'][] = ['label' => \quoma\arya\zone\ZoneModule::t('Zones'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="zone-create">

    <div class="row">
    	<div class="col-sm-8 col-sm-offset-2">
		    <h1><?= Html::encode($this->title) ?></h1>

		    <?= $this->render('_form', [
		        'model' => $model,
		    ]) ?>
    	</div>
    </div>

</div>

src/views/zone/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use quoma\arya\zone\models\Location;

/* @var $this yii\web\View */
/* @var $searchModel quoma\arya\zone\models\search\ZoneSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = \quoma\arya\zone\ZoneModule::t('Zones');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="zone-index">

    <div class="title">
        <h1><?= Html::encode($this->title) ?></h1>

        <p>
            <?= Html::a("<span class='glyphicon glyphicon-plus'></span> " . Yii::t('app', 'Create {modelClass}', ['modelClass' => \quoma\arya\zone\ZoneModule::t('Zone')]), ['create'], ['class' => 'btn btn-success']) ?>
        </p>
    </div>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'options' => ['class' => 'table-responsive'],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute'=>'name',
                'format'=>'html'
            ],
            [
                'class' => 'quoma\core\grid\ActionColumn',
            ],
            
        ],
    ]); ?>

</div>

src/views/zone/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model quoma\arya\zone\models\Zone */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => \quoma\arya\zone\ZoneModule::t('Zone'),
]) . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => \quoma\arya\zone\ZoneModule::t('Zones'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->zone_id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="zone-update">

    <div class="row">
    	<div class="col-sm-8 col-sm-offset-2">
		    <h1><?= Html::encode($this->title) ?></h1>

		    <?= $this->render('_form', [
		        'model' => $model,
                'membersDataProvider' => $membersDataProvider
		    ]) ?>
    	</div>
    </div>

</div>

src/views/zone/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model quoma\arya\zone\models\Zone */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => \quoma\arya\zone\ZoneModule::t('Zones'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="zone-view">

    <div class="title">
        <h1><?= Html::encode($this->title) ?></h1>

        <p>
            <?= Html::a("<span class='glyphicon glyphicon-pencil'></span> " . Yii::t('app', 'Update'), ['update', 'id' => $model->zone_id], ['class' => 'btn btn-primary']) ?>
            <?php if($model->deletable) echo Html::a("<span class='glyphicon glyphicon-remove'></span> " . Yii::t('app', 'Delete'), ['delete', 'id' => $model->zone_id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]) ?>
        </p>
    </div>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'zone_id',
            'name',
        ],
    ]) ?>

</div>